#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/kubernetes
- name: Install required packages for Minikube
  apt:
    name:
      - curl
      - apt-transport-https
      - conntrack
    state: present
    update_cache: true

- name: Download kubectl binary
  get_url:
    url: https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'

- name: Install Minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    mode: '0755'

- name: Ensure Minikube is started
  shell: |
    minikube status | grep -q "host: Running" || minikube start --driver=docker
  environment:
    CHANGE_MINIKUBE_NONE_USER: "true"
